### ISSUE TITLE
crfsuite / nametagger

### ISSUE THREAD

**Issue by jwijffels** [pprablanc/NER---GENIA#1]
are you aware of the R packages crfsuite and nametagger and that you can also build a pos tagger with udpipe https://cran.r-project.org/web/packages/udpipe/vignettes/udpipe-train.html
https://cran.r-project.org/web/packages/crfsuite/index.html
https://cran.r-project.org/web/packages/nametagger/index.html

**Comment by pprablanc** [comment]
Sure I know about crfsuite and udpipe, we have used it in the project. I think I have uploaded the wrong folder, this is why it is missing CRF experiments. I'll clean this up. But thanks for the advice anyway :)

**Comment by jwijffels** [comment]
I see that you have built a markov model.
Maybe you can indicate to your teacher that this package https://cran.r-project.org/web/packages/nametagger/index.html exactly has that implemented already. Probably he's not aware either that this existed.
Let me close this. I just accidently bumped on to this repo while looking from some doc2vec code while I saw you just worked on this https://github.com/pprablanc/doc_embedding_topic_mod/blob/main/Rapport_TER.pdf while I just created this https://github.com/bnosac/doc2vec maybe that's of interest to you.

**Comment by pprablanc** [comment]
We were 3 on this project and working mostly autonomous. I didn't carry out the work on HMM but I know that we had some trouble using an existing library. That is why Yang re-implemented the hmm algorithm. Maybe we tried nametagger package, I'm not sure (it was on 2018). However I'm interested in doc2vec, I'll answer on that on the appropriate thread.

**Comment by jwijffels** [comment]
pkg nametagger was only on cran since 2020-06-04 so must have been another pkg
